version: '3.8'
services:
  web-site-ingelec:
    build: .
    restart: always
    ports:
      - "4321:4321"
    environment:
      NODE_ENV: production
    networks:
      - websiteingelec-network
networks:
  websiteingelec-network:
    driver: bridge
    